# Generated by Django 4.2.3 on 2023-07-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
