# Generated by Django 4.2.3 on 2023-07-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articulo_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
