# Generated by Django 4.2.3 on 2023-07-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comentario_estado_alter_comentario_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.png', upload_to='media'),
        ),
    ]
