# Generated by Django 4.2.3 on 2023-07-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_usuarios_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='bajada',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='avatar',
            field=models.ImageField(default='/media/avatars/default_avatar.png', upload_to='media/avatars'),
        ),
    ]
