# Generated by Django 4.2.3 on 2023-07-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_articulo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='etiqueta',
            field=models.ManyToManyField(to='blog.etiqueta'),
        ),
    ]
